### ISSUE TITLE
Add telescope picker to show all org files to pick from to open

### ISSUE THREAD

**Issue by GitMurf** [nvim-orgmode/telescope-orgmode.nvim#11]
@lyz-code one feature I was thinking of implementing is an option to view all org files in a Telescope picker to choose from to open. Basically just like core telescope find files but for your org files. I find most of the time I actually end up using the search headlines feature just so I can do this when it would be cleaner to just have a simple picker with a simple list of org file names with the benefit of using telescopes fuzzy find.

Thoughts?

**Comment by lyz-code** [comment]
Hii, I find that the generic find files is enough for my workflow but if you have this need I'm fine merging it as long as it doesn't replace the current behaviour

**Comment by GitMurf** [comment]
yeah the proposal would just be an added feature and not change any of the current features. there would be a third option called something like: `orgmode.open_org_file` or `orgmode.find_org_files`. @lyz-code do you have thoughts / preferences on a name for it?

**Comment by lyz-code** [comment]
I feel that `orgmode.find_org_files` feels more natural

**Comment by seflue** [comment]
@GitMurf This feature was already in the plugin before I overtook the maintenance. But it wasn't documented. Now [it is](https://github.com/nvim-orgmode/telescope-orgmode.nvim?tab=readme-ov-file#toggle-between-headline-and-org-file-search). It is basically usable for all three major operations you can currently do with telescope-orgmode: navigate, refile and insert link.

**Comment by seflue** [comment]
You can now achieve this by `:Telescope orgmode search_headings mode=orgfiles` or by creating a keymap:
```lua
vim.keymap.set("n", "of", function()
  require("telescope").extensions.orgmode.search_headings({ mode = "orgfiles" })
end)
```
