### ISSUE TITLE
The core configuration of this Telescope extension is setup incorrectly

### ISSUE THREAD

**Issue by GitMurf** [nvim-orgmode/telescope-orgmode.nvim#13]
@lyz-code fyi the actual core structure and architecture of this telescope extension is setup in correctly in several ways. Maybe a couple years ago things were done differently but it definitely does not adhere to the specs of today for creating telescope extensions.

This issue will represent re-structuring the extension to today's standards / requirements for the telescope extensions API.

I will try to do a PR this weekend when I have some time.

**Comment by lyz-code** [comment]
That would be lovely, thank you so much <3

**Comment by seflue** [comment]
@GitMurf Any news on this?

**Comment by GitMurf** [comment]
> @GitMurf Any news on this?

No I am sorry but orgmode ended up not being something that stuck for me. I am back to taking all my notes in Obsidian and Notion.

If I ever come back to using orgmode I will take a deeper look.

**Comment by seflue** [comment]
@GitMurf I was just wondering what you meant with your statement:

> the actual core structure and architecture of this telescope extension is setup in correctly in several ways.

I never wrote an Telescope extension myself, but I have several ideas and actually requirements regarding Orgmode and to get started, I worked through Telescopes [development.md](https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md). 

If I compare this to the plugin code, I actually don't see pressing issues. One might complain, that the meat of the code is actually living directly in the `telescope/_extensions` folder. But besides that, I can't see, how the Telescope API is used fundamentally wrong. But as I said, I don't have real experience in developing Telescope plugins. 

Would you mind to point me to the biggest issues you see in the architecture and in the code of this plugin? And do you have a good example to learn from? The [Telescope tutorial](https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md#guide-to-your-first-picker) is too small and the telescope-fzf-native plugin they're referring to is actually too big.

I would actually love to do some refactoring on my own, but would appreciate your help in getting the structure right to the current standards.

**Comment by seflue** [comment]
@lyz-code I created a PR #15, what do you think? @GitMurf Would you mind to take a look, if the structure is now more according to what you imagined?

**Comment by seflue** [comment]
Because we had a major refactoring, which should fix most of the architectural problems, I will close this issue.

**Comment by GitMurf** [comment]
@seflue i did a quick review of your work and it looks great! This is what i envisioned. Nice work!
