### ISSUE TITLE
Host nvim-telescope unter the nvim-orgmode organisation

### ISSUE THREAD

**Issue by seflue** [nvim-orgmode/telescope-orgmode.nvim#18]
Because the original creator of the plugin is gone, I could imagine it would be better to host the plugin within the nvim-orgmode organiszation. @kristijanhusak, @lyz-code Would you be open for this idea? I will of course continue maintaining it, because it is already part of my daily workflow and I have quite some ideas to improve it.

**Comment by kristijanhusak** [comment]
I'm ok with that idea, only @lyz-code needs to give me admin access to this repo, so I can switch it to organization.

**Comment by lyz-code** [comment]
It makes total sense, thanks for improving so much this project <3

**Comment by lyz-code** [comment]
@kristijanhusak I made you collaborator, I don't know if those are enough permissions, if they aren't can you please guide me through the steps required?

Thanks

**Comment by kristijanhusak** [comment]
@lyz-code I accepted the invitation. You should be able to promote me to an admin now from the settings.

**Comment by lyz-code** [comment]
![github](https://github.com/lyz-code/telescope-orgmode.nvim/assets/24810987/9ec2a4bf-b017-430b-901c-4c40c490b783)

I don't see how. I've tried to do the transfer myself but I don't have permissions to create public repos in the nvim-orgmode org either

**Comment by kristijanhusak** [comment]
Yes, you can transfer it to me also and I'll take it from there.

**Comment by lyz-code** [comment]
Done :)

**Comment by kristijanhusak** [comment]
Transfer done https://github.com/nvim-orgmode/telescope-orgmode.nvim

**Comment by kristijanhusak** [comment]
Thanks!

**Comment by seflue** [comment]
@kristijanhusak Because I am now the maintainer of the plugin, can you also make me admin of this project?

**Comment by kristijanhusak** [comment]
@seflue sure, promoted you to admin.
